#!/usr/bin/env node
// The stylesheet, TWICE: as `dist/omnibox.css` (exported at `./omnibox.css`, for a
// consumer with a real CSS pipeline) and as `src/omniboxStyles.generated.ts` — a JS
// module carrying the same bytes as a string, which the component injects once.
//
// WHY THE JS COPY EXISTS, AND WHY IT IS NOT BELT-AND-BRACES. The published
// `dist/Omnibox.js` used to carry `import './omnibox.css'`, and on immediately.run that
// took down the front door: the sandbox bundler followed the specifier, fetched the
// stylesheet, and EVALUATED IT AS JAVASCRIPT — `SyntaxError: Unexpected token '.'` on
// the first selector, with the whole app dead behind it (prod and local alike, from
// landing-page@d2f43bb on 2026-09-06 until this change). A library published for a
// platform that runs untrusted code in a browser bundler cannot assume the consumer has
// a CSS loader; the only thing it can rely on is JS. So the SHIPPED path is the string,
// and `dist/omnibox.css` stays for consumers who prefer to own the cascade.
//
// The generated module is committed, so `npm test`/`tsc` see it without a build step,
// and `npm run check:css-parity` fails if it drifts from the .css.
//
// TWO PHASES, because `tsup` cleans `dist/`. Without a flag this writes only the TS
// module — which must exist BEFORE tsup runs, since tsup bundles it. `--dist` copies the
// stylesheet into `dist/`, and must run AFTER, or the clean deletes it. `build` does
// both, in that order; getting it wrong ships a package whose `./omnibox.css` export
// 404s, which is silent until a consumer imports it.
import { copyFileSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const cssPath = join(root, 'src', 'omnibox.css');
const css = readFileSync(cssPath, 'utf8');

if (process.argv.includes('--dist')) {
  mkdirSync(join(root, 'dist'), { recursive: true });
  copyFileSync(cssPath, join(root, 'dist', 'omnibox.css'));
  console.log(`Copied src/omnibox.css -> dist/omnibox.css (${css.length} bytes)`);
  process.exit(0);
}

const generated = `// GENERATED by scripts/build-css.mjs from src/omnibox.css — do not edit by hand.
// Committed so tests and \`tsc\` see it without a build step; \`npm run check:css-parity\`
// fails when it drifts. See that script for why the styles ship as a string.

export const OMNIBOX_CSS = ${JSON.stringify(css)};
`;
writeFileSync(join(root, 'src', 'omniboxStyles.generated.ts'), generated);
console.log(`Baked ${css.length} bytes into src/omniboxStyles.generated.ts`);
